// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/wangjie/mySpace/sd-hooks/node_modules/.pnpm/dumi@2.2.17_@babel+core@7.23.6_@types+node@20.11.5_eslint@7.2.0_jest@29.4.1_prettier@2.8.8_re_kmvipu4kv2rgrmycn66hmtva44/node_modules/dumi/theme-default/slots/Footer/index.js';
